const SUPA="https://sqeopvadmrzikmjjekig.supabase.co";
const KEY="sb_publishable_er0tmwrneNLBFEPdWWxwZg_nhkzNvYd";
const ASSET=SUPA+"/storage/v1/object/public/wedding-media/static/";
const MEDIA=SUPA+"/storage/v1/object/public/wedding-media/";
const H={apikey:KEY,"Content-Type":"application/json"};
const state={loading:true,tab:"홈",settings:null,profiles:[],accounts:[],guestbook:[],photos:[],placements:[],visits:{today:0,total:0},modal:null,adminToken:localStorage.getItem("wedding_admin_token")||"",adminData:null};

const q=s=>document.querySelector(s);
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const pub=p=>MEDIA+p;
function sess(k){let v=localStorage.getItem(k);if(!v){v=crypto.randomUUID();localStorage.setItem(k,v)}return v}
async function rest(path,opt={}){const r=await fetch(SUPA+"/rest/v1/"+path,{...opt,headers:{...H,...(opt.headers||{})}});if(!r.ok)throw new Error(await r.text());const t=await r.text();return t?JSON.parse(t):null}
async function fn(name,body){const r=await fetch(SUPA+"/functions/v1/"+name,{method:"POST",headers:H,body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"request");return d}
async function rpc(name,body){return rest("rpc/"+name,{method:"POST",body:JSON.stringify(body)})}
function dateText(){const s=state.settings;if(!s)return"";const d=new Date(s.wedding_date+"T"+String(s.wedding_time).slice(0,5)+":00+09:00");const w=["SUN","MON","TUE","WED","THU","FRI","SAT"];return `${d.getFullYear()}.${String(d.getMonth()+1).padStart(2,"0")}.${String(d.getDate()).padStart(2,"0")} ${w[d.getDay()]} ${String(s.wedding_time).slice(0,5)}`}
function dday(){if(!state.settings)return 0;return Math.max(0,Math.ceil((new Date(state.settings.wedding_date+"T00:00:00+09:00")-Date.now())/86400000))}
async function loadPublic(){
 const day=new Date().toLocaleDateString("sv-SE");
 try{const v=await rpc("register_visit",{p_day:day});if(v&&v[0])state.visits=v[0]}catch{}
 const [settings,profiles,accounts,guestbook,photos,placements]=await Promise.all([
  rest("wedding_settings?select=*&id=eq.1"),
  rest("profile_settings?select=*&order=side.asc"),
  rest("wedding_accounts?select=*&order=side.asc,account_key.asc"),
  rest("guestbook?select=id,name,message,source_label,created_at,updated_at&order=id.desc&limit=100"),
  rest("photos?select=*&order=sort_order.asc,id.asc"),
  rest("home_placements?select=*&order=id.asc")
 ]);
 state.settings=settings[0];state.profiles=profiles;state.accounts=accounts;state.guestbook=guestbook;state.photos=photos;state.placements=placements;
}
function Loading(){return `<div class="loading-page"><div class="loading-inner"><div class="knock">KNOCK KNOCK</div><h1>범수 <span>♥</span> 서영의 집</h1><div class="loading-art"><img src="${ASSET}loading-door.png"></div><div class="heart-loader">${Array.from({length:10},(_,i)=>`<span style="animation-delay:${i*.16}s">♥</span>`).join("")}</div><strong>문 여는 중...</strong><small>Loading...</small><button onclick="finishLoading()">건너뛰기</button></div></div>`}
function finishLoading(){state.loading=false;render()}
function shell(c){return `<main class="site-shell"><section class="minihome"><header class="titlebar"><button class="home-nav-btn" onclick="goTab('홈')"><img src="${ASSET}home-icon.png"></button><b>범수 ♥ 서영의 미니홈피</b><span class="header-charm">♡ 2027</span></header><nav class="tabs">${["홈","프로필","사진첩","방명록","예식 안내"].map(t=>`<button class="${state.tab===t?"active":""}" onclick="goTab('${t}')">${t}</button>`).join("")}</nav><div class="visit-counter">TODAY <b>${state.visits.today}</b> | TOTAL <b>${state.visits.total}</b></div>${c}</section></main>`}
function home(){return `<div class="home-page">
<section class="wedding-card"><div class="profile-visual"><div class="mini-pair"><img src="${ASSET}groom.png"><img src="${ASSET}bride.png"></div></div><div class="wedding-copy"><h1>범수 <span>♥</span> 서영</h1><p>${esc(dateText())}</p><p>${esc(state.settings?.place_name||"")}</p></div><div class="d-day">D-${dday()}</div></section>
<section class="today-line"><b>오늘의 한마디</b><span>우리 결혼합니다 💍</span><i>♡ ♥ ♡</i></section>
<button class="room-stage" onclick="if(!window.roomMiniDragSkipClick)openHomePopup();window.roomMiniDragSkipClick=false"><img class="room-bg" src="${ASSET}room.png"><div class="room-mini groom-mini" data-mini="groom"><span class="mini-heart groom-heart">♥</span><img src="${ASSET}groom.png"></div><div class="room-mini bride-mini" data-mini="bride"><span class="mini-heart bride-heart">♥</span><img src="${ASSET}bride.png"></div><div class="room-toast">♥ 벌써 ${state.visits.total}명이 마음을 남겼어요</div></button>
<section class="invitation-card"><h2>📖 <span>초대장</span></h2><p>각자 서로 다른 길을 걸어온 저희가 이제 부부의 연으로 한 길을 걸어가고자 합니다. 소중한 날, 함께해 주세요.</p></section>
<div class="home-actions"><button class="house" onclick="openHomePopup()">🏠 신혼집</button><button onclick="goTab('예식 안내')">📍 오시는 길</button><button class="friend" onclick="openFriend()">💌 일촌 신청<i></i></button></div></div>`}
function profile(){return `<div class="page"><div class="section-head"><small>PROFILE</small><h2>내 소개</h2></div>${state.profiles.map(p=>{const ph=state.photos.find(x=>x.kind==="profile_"+p.side);return `<article class="profile-card"><div class="profile-photo"><img src="${ph?pub(ph.storage_path):(p.side==="groom"?ASSET+"groom.png":ASSET+"bride.png")}"></div><div><span class="profile-role">${esc(p.role)}</span><p>${esc(p.relation)}</p><h3>${esc(p.name)}</h3><p>Birthday · ${esc(p.birthday)}</p><p>MBTI · ${esc(p.mbti)}</p><p>${esc(p.intro||"")}</p><div class="mini-qa">${[1,2,3].map(i=>`<div><b>${esc(p["q"+i+"_question"])}</b><p>${esc(p["q"+i+"_answer"])}</p></div>`).join("")}</div></div></article>`}).join("")}</div>`}
function photos(){const a=state.photos.filter(x=>x.kind==="album");return `<div class="page"><div class="section-head"><small>PHOTO ALBUM</small><h2>우리의 사진첩</h2></div><div class="photo-grid">${a.map(p=>`<figure class="photo-card"><img src="${pub(p.storage_path)}"><figcaption>${esc(p.caption||"")}</figcaption></figure>`).join("")}</div></div>`}
let guestSubmitting=false;
function guestbook(){const tok=JSON.parse(localStorage.getItem("guestbook_tokens")||"{}");return `<div class="page"><div class="section-head"><small>GUEST BOOK</small><h2>축하 한마디 남기기</h2></div><div class="guest-form"><label>이름<input id="gb-name" maxlength="30"></label><label>한마디<textarea id="gb-msg" maxlength="500"></textarea></label><button id="gb-submit" onclick="createGuest()">한마디 남기기</button></div><div class="guest-list">${state.guestbook.map((g,i)=>`<article class="guest-entry"><div class="guest-avatar">${i%2?"♥":"☺"}</div><div><div class="guest-row"><b>${esc(g.name)}</b><span>No.${state.guestbook.length-i}</span></div><p>${esc(g.message)}</p><div class="guest-foot"><small>${String(g.created_at).slice(0,16).replace("T"," ")}</small>${tok[g.id]?`<span><button onclick="editGuest(${g.id})">수정</button><button onclick="deleteGuest(${g.id})">삭제</button></span>`:""}</div></div></article>`).join("")}</div></div>`}
async function createGuest(){if(guestSubmitting)return;const n=q("#gb-name").value.trim(),m=q("#gb-msg").value.trim();if(!n||!m)return alert("이름과 한마디를 모두 작성해주세요.");guestSubmitting=true;const b=q("#gb-submit");if(b){b.disabled=true;b.textContent="등록 중..."}try{const d=await fn("guestbook",{action:"create",name:n,message:m,website:""});const t=JSON.parse(localStorage.getItem("guestbook_tokens")||"{}");t[d.entry.id]=d.edit_token;localStorage.setItem("guestbook_tokens",JSON.stringify(t));await refreshGuest()}finally{guestSubmitting=false}}
async function refreshGuest(){state.guestbook=await rest("guestbook?select=id,name,message,source_label,created_at,updated_at&order=id.desc&limit=100");render()}
async function editGuest(id){const e=state.guestbook.find(x=>x.id===id),t=JSON.parse(localStorage.getItem("guestbook_tokens")||"{}");if(!e||!t[id])return;const n=prompt("이름",e.name);if(n===null)return;const m=prompt("한마디",e.message);if(m===null)return;await fn("guestbook",{action:"update",id,edit_token:t[id],name:n,message:m});await refreshGuest()}
async function deleteGuest(id){if(!confirm("삭제할까요?"))return;const t=JSON.parse(localStorage.getItem("guestbook_tokens")||"{}");await fn("guestbook",{action:"delete",id,edit_token:t[id]});delete t[id];localStorage.setItem("guestbook_tokens",JSON.stringify(t));await refreshGuest()}
function guide(){const s=state.settings,d=new Date(s.wedding_date+"T00:00:00+09:00"),y=d.getFullYear(),m=d.getMonth(),first=new Date(y,m,1).getDay(),last=new Date(y,m+1,0).getDate(),target=d.getDate(),cells=Math.ceil((first+last)/7)*7;const days=Array.from({length:cells},(_,i)=>{const n=i-first+1;return `<span class="${n===target?"wedding-day":""}">${n>0&&n<=last?n:""}</span>`}).join("");const acc=side=>{const arr=state.accounts.filter(a=>a.side===side&&(a.bank_name||a.account_number||a.holder));return `<details class="account-box"><summary>${side==="bride"?"신부측 계좌":"신랑측 계좌"} <span>＋</span></summary><div>${arr.map(a=>`<div class="account-line"><div><b>${esc(a.label)}</b><span>${esc(a.bank_name)} · 예금주 ${esc(a.holder)}</span><strong>${esc(a.account_number)}</strong></div></div>`).join("")||"<p>계좌 정보가 등록되면 표시됩니다.</p>"}</div></details>`};return `<div class="page"><div class="section-head"><small>WEDDING INFO</small><h2>예식 안내</h2></div><div class="guide-calendar"><div class="calendar-title">${d.toLocaleString("en-US",{month:"long"}).toUpperCase()} ${y}</div><div class="calendar-week">${["SUN","MON","TUE","WED","THU","FRI","SAT"].map(x=>`<span>${x}</span>`).join("")}</div><div class="calendar-grid">${days}</div></div><div class="guide-info"><article><span>DATE & TIME</span><b>${esc(dateText())}</b></article><article><span>PLACE</span><b>${esc(s.place_name)}</b><p>${esc(s.place_detail)}</p></article></div><h3>마음 전하실 곳</h3>${acc("bride")}${acc("groom")}</div>`}
function openFriend(){state.modal="friend";render()}function openHomePopup(){state.modal="home";render()}function closeModal(){state.modal=null;render()}
function modal(){if(!state.modal)return"";return `<div class="modal-dim" onclick="closeModal()"><div class="pixel-popup" onclick="event.stopPropagation()"><div class="popup-overlay"><div class="popup-bar"><b>${state.modal==="friend"?"일촌 신청":"신혼집"}</b></div><div class="popup-content">${state.modal==="friend"?`<h2>💌 범수 ♥ 서영</h2><p>님이 일촌 신청을 보냈어요</p><p>응답은 다른 하객에게 공개되지 않고 신랑 신부에게만 전달돼요.</p><button class="primary" onclick="location.href='?view=rsvp'">일촌 신청하러 가기</button>`:`<h2>🏠 범수 ♥ 서영의 신혼집에 입장하시겠어요?</h2><button class="primary" onclick="location.href='?view=house'">입장하기</button>`}<button class="secondary" onclick="closeModal()">나중에</button></div></div></div></div>`}
function goTab(t){state.tab=t;state.modal=null;history.replaceState({},"",location.pathname);render();scrollTo(0,0)}
function initMiniDrag(){const room=q(".room-stage"),minis=[...document.querySelectorAll(".room-mini")];if(!room)return;minis.forEach(mini=>{if(mini.dataset.ready)return;mini.dataset.ready="1";const key="wedding-mini-position-"+mini.dataset.mini;requestAnimationFrame(()=>{const maxX=Math.max(0,room.clientWidth-mini.offsetWidth),maxY=Math.max(0,room.clientHeight-mini.offsetHeight);const saved=localStorage.getItem(key);if(saved){try{const p=JSON.parse(saved);mini.style.left=Math.max(0,Math.min(maxX,p.x*maxX))+"px";mini.style.top=Math.max(0,Math.min(maxY,p.y*maxY))+"px";mini.style.bottom="auto";mini.style.transform="none"}catch{}}});let active=false,sx=0,sy=0,sl=0,st=0,moved=false;mini.addEventListener("pointerdown",e=>{e.preventDefault();e.stopPropagation();active=true;moved=false;sx=e.clientX;sy=e.clientY;sl=mini.offsetLeft;st=mini.offsetTop;mini.setPointerCapture?.(e.pointerId);mini.classList.add("dragging")});mini.addEventListener("pointermove",e=>{if(!active)return;const dx=e.clientX-sx,dy=e.clientY-sy;if(Math.abs(dx)+Math.abs(dy)>4)moved=true;const maxX=Math.max(0,room.clientWidth-mini.offsetWidth),maxY=Math.max(0,room.clientHeight-mini.offsetHeight);mini.style.left=Math.max(0,Math.min(maxX,sl+dx))+"px";mini.style.top=Math.max(0,Math.min(maxY,st+dy))+"px";mini.style.bottom="auto";mini.style.transform="none"});const done=()=>{if(!active)return;active=false;mini.classList.remove("dragging");if(moved){window.roomMiniDragSkipClick=true;const maxX=Math.max(1,room.clientWidth-mini.offsetWidth),maxY=Math.max(1,room.clientHeight-mini.offsetHeight);localStorage.setItem(key,JSON.stringify({x:(parseFloat(mini.style.left)||0)/maxX,y:(parseFloat(mini.style.top)||0)/maxY}))}};mini.addEventListener("pointerup",done);mini.addEventListener("pointercancel",done)})}
function rsvp(){return `<div class="page"><div class="section-head"><small>FRIEND REQUEST</small><h2>일촌 신청</h2></div><p>일촌 신청 화면은 복구 중입니다. 청첩장 홈으로 돌아가 주세요.</p><button class="primary" onclick="location.href=location.pathname">청첩장으로 돌아가기</button></div>`}
function house(){return `<div class="page"><div class="section-head"><small>NEWLYWED HOME</small><h2>신혼집 꾸미기</h2></div><p>신혼집 꾸미기 화면은 복구 중입니다. 청첩장 홈으로 돌아가 주세요.</p><button class="primary" onclick="location.href=location.pathname">청첩장으로 돌아가기</button></div>`}
function render(){const p=new URLSearchParams(location.search);if(state.loading){q("#app").innerHTML=Loading();return}if(p.get("view")==="rsvp"){q("#app").innerHTML=shell(rsvp());return}if(p.get("view")==="house"){q("#app").innerHTML=shell(house());return}const c=state.tab==="홈"?home():state.tab==="프로필"?profile():state.tab==="사진첩"?photos():state.tab==="방명록"?guestbook():guide();q("#app").innerHTML=shell(c)+modal();if(state.tab==="홈")initMiniDrag()}
(async()=>{q("#app").innerHTML=Loading();try{await Promise.all([loadPublic(),new Promise(r=>setTimeout(r,2300))])}catch(e){console.error(e)}state.loading=false;render()})();